mod : Add new restriction type Reset Rating
verdie-g/crpg pull request #1136
Opened 2023-07-09 01:29 UTC by namidaka

2023-07-10 22:04 UTC, verdie-g requested changes
A restriction is something that lasts in time and also something that restricts the user for doing an action so resetting a rating doesn't fit that.

2023-07-11 03:22 UTC, namidaka commented
> A restriction is something that lasts in time and also something that restricts the user for doing an action so resetting a rating doesn't fit that.

What i like about restricting is that they get logged with a reason, easy to access for moderator. Any suggestion to achieve this?

2023-07-11 15:47 UTC, verdie-g commented
Maybe that can be covered by https://github.com/verdie-g/crpg/issues/933 ?

2023-07-11 16:43 UTC, or2e commented
and merge it with https://github.com/verdie-g/crpg/issues/985

2023-07-11 20:38 UTC, closed without merging