webui: new item filter
verdie-g/crpg pull request #1143
Opened 2023-07-12 01:38 UTC by or2e

2023-07-12 01:51 UTC, verdie-g commented on src/WebUI/src/services/item-search-service/indexator.ts
> +const prior = new Date().setDate(new Date().getDate() - isNewItemDays);
newItemDateThreshold 🤷

2023-07-14 00:31 UTC, or2e commented on src/WebUI/src/pages/shop.vue
> -import { WeaponUsage, type ItemFlat, ItemCompareMode } from '@/models/item';
`ItemCompareMode` - unused

2023-07-14 14:15 UTC, verdie-g requested changes

2023-07-14 14:15 UTC, verdie-g commented on src/WebUI/locales/en.yml
> +      description: 'Show items added within {days} days'
```suggestion
      description: 'Show items added or reworked within the last {days} days'
```
Same for CN/RU

2023-07-14 14:15 UTC, verdie-g commented on src/WebUI/src/services/item-search-service/indexator.ts
> +  if (item.type === ItemType.Shield && isLargeShield(item)) {
That check is already done in isLargeShield

2023-07-16 14:34 UTC, verdie-g approved these changes

2023-07-16 14:34 UTC, merged