1144 leaderboard filter by char class
verdie-g/crpg pull request #1156
Opened 2023-07-16 15:43 UTC by or2e

![image](https://github.com/verdie-g/crpg/assets/33551334/1d44a4e8-e388-45d2-bcc7-c45d4313e224)

2023-07-16 15:53 UTC, or2e commented on src/WebApi/Controllers/LeaderboardController.cs
> -using Crpg.Application.Games.Commands;
unused

2023-07-16 18:55 UTC, namidaka requested changes

2023-07-16 18:55 UTC, namidaka commented on src/WebApi/Controllers/LeaderboardController.cs
> +    )
this solves the stylecop warning
```suggestion
    public Task<ActionResult<Result<IList<CharacterPublicViewModel>>>> GetLeaderboard(
        [FromQuery] Region? region,
        [FromQuery] CharacterClass? characterClass)
```

2023-07-17 01:34 UTC, namidaka reviewed
All good for me, what does @verdie-g  think?

2023-07-17 01:49 UTC, verdie-g commented
I'll have a look tomorrow

2023-07-17 10:33 UTC, verdie-g requested changes

2023-07-17 10:33 UTC, verdie-g commented on src/Application/Characters/Queries/GetLeaderboardQuery.cs
> +                .Where(c => req.CharacterClass == null || req.CharacterClass == c.Class)
You can merge that with the previous where clause

2023-07-18 00:14 UTC, verdie-g approved these changes

2023-07-18 00:33 UTC, merged