mod: improve translate RU
verdie-g/crpg pull request #1180
Opened 2023-07-20 22:12 UTC by or2e

2023-07-20 22:15 UTC, or2e commented on src/Module.Server/ModuleData/Languages/RU/std_module_strings_xml-rus.xml
> +    <string id="xAnUFQt2" text="{COUNT} игроков перешело в команду атакующих{newline}" />
I'm missing the 3rd pluralization option here.

`0 игроков`
`1 игрок`
`2 игрока`
`5 игроков` 

I can't rephrase it

2023-07-21 01:20 UTC, verdie-g approved these changes
Thanks!

2023-07-21 01:20 UTC, verdie-g commented on src/Module.Server/ModuleData/Languages/RU/std_module_strings_xml-rus.xml
> +    <string id="2m5CdjYa" text="Вы не смогли позволить себе ремонт {?IS_PLURAL}предмета{?}предметов{\\?} {ITEMS}, в результате чего он сломался и был снят. Вам необходимо посетить веб-сайт и экипиров
`{\\?}` the double slash is only for C# to scape the backslash. `{\?}` in xml.

2023-07-21 01:21 UTC, verdie-g requested changes
Wrong button

2023-07-21 11:59 UTC, verdie-g commented on src/Module.Server/ModuleData/Languages/RU/std_module_strings_xml-rus.xml
> +    <string id="xAnUFQt2" text="{COUNT} игроков перешело в команду атакующих{newline}" />
Lol I just understood what you meant. Interesting concept. Not sure how TW dealt with that .

2023-07-21 11:59 UTC, verdie-g approved these changes

2023-07-21 11:59 UTC, merged