[WIP] webui: activity-logs-ui
verdie-g/crpg pull request #877
Opened 2023-04-04 22:42 UTC by or2e

2023-04-07 06:36 UTC, verdie-g requested changes
Nice! I've suggested some improvements to make it easier for moderators.

OPT -> optional

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/models/activity-logs.ts
> +  metadata: Record<string, any>;
string -> string

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/services/activity-logs-service.ts
> +  return (await get<ActivityLog[]>(`/activity-logs?${params}`)).map(al => ({
OPT: you could use GET /users to get user names and pictures

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/pages/moderator/logs.vue
> +            placeholder="Comma-separated values"
What would be the workflow for a moderator to get  a user id?

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/pages/moderator/logs.vue
> +      fromDate.setDate(fromDate.getDate() - 1);
Can you use the last 5 minutes instead? This request risk to be quite expensive

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/pages/moderator/logs.vue
> +            #default="{ row: activityLog }: { row: ActivityLog }"
OPT: add an interaction on a cell to "filter by this user", "filter by this type"

2023-04-07 06:36 UTC, verdie-g commented on src/WebUI/src/pages/moderator/logs.vue
> +            <tr v-for="(value, key) in activityLog.metadata" class="">
OPT: have a template for each log type so you can display "User X team hit user Y for Z damage".

2023-05-08 00:32 UTC, or2e commented
re-worked
updated the description

2023-05-08 00:34 UTC, or2e commented on src/WebUI/locales/en.yml
> +activityLog:
Only for the `en` dict. The others will inherit it

2023-05-08 00:37 UTC, or2e commented on src/WebUI/src/components/moderator/CreateRestrictionForm.vue
>  <template>
Here I just removed the wrapper `<div class="mb-12 space-y-8">`
as this component is now in the modal window

there are no more edits in this file

2023-05-08 00:38 UTC, or2e commented on src/WebUI/src/components/moderator/UserFinder.vue
made the user search form a dedicate component

2023-05-08 00:39 UTC, or2e commented on src/WebUI/src/pages/moderator/find-user.vue
moved the functionality to the `UserFinder` component, since it is now used in several places

2023-05-11 00:19 UTC, verdie-g requested changes

2023-05-11 00:19 UTC, verdie-g commented on src/WebUI/locales/en.yml
> +    CharacterDeleted: 'The character {2} was deleted. Level {0} generation {1}'
The character {2}, level {0}, generation {1}, was deleted ?

2023-05-11 00:19 UTC, verdie-g commented on src/WebUI/locales/en.yml
> +    CharacterRespecialized: 'The character {1} has been respecialized for {0}'
was respecialized
to keep the same tense as others

2023-05-11 00:19 UTC, verdie-g commented on src/WebUI/src/services/activity-logs-service.ts
> +    if (l.type === ActivityLogType.TeamHit) {
What do you think about looking for know metadata key such as 'targetUserId'. That would be more future proof

2023-05-11 00:19 UTC, verdie-g commented on src/WebUI/src/services/activity-logs-service.ts
> +  const users = await getUsersByIds([...new Set([...(payload.userId ?? []), ...usersIdsFromLogs])]);
👁🩸

2023-05-11 15:05 UTC, verdie-g approved these changes

2023-05-11 15:05 UTC, merged