Adjustes project.mbproj
verdie-g/crpg pull request #887
Opened 2023-04-09 18:24 UTC by Meowkov

Changed project.mbproj to correctly load combat_parameters.xml and native_parameters.xml from the cRPG files.
Copied the native versions of both files to ModuleData, changes to the variables in both files will now work.

2023-04-09 18:35 UTC, verdie-g requested changes
Could you specify which variables were changed? I'll try to avoid copying the whole file when I get back home (in a week).

2023-04-09 18:41 UTC, Meowkov commented
No variables were changed, this is 1:1 the native files ready for future changes.
During testing on my end, having custom files with only the variables we touched, did not consistently work.
We can look into approaching this differently when you are back, if you see another way.

2023-04-10 08:07 UTC, verdie-g requested changes
Ok I'll have a look when I'm back

2023-04-10 08:07 UTC, verdie-g commented on src/Module.Server/ModuleData/project.mbproj
> +  <file id="soln_combat_system" name="ModuleData/native_parameters.xml" type="native_parameters" />
What's that btw?

2023-06-27 20:56 UTC, Meowkov commented
Turns out this works fine as it is already implemented.

2023-06-27 20:56 UTC, closed without merging