mod : headshot ranged bonus 2x => 1.6, melee 1.5x => 1.3x
verdie-g/crpg pull request #917
Opened 2023-04-26 11:16 UTC by namidaka

2023-04-26 11:18 UTC, namidaka commented
Discussed with community here : ![image](https://user-images.githubusercontent.com/47090987/234559519-c8821974-cce8-4aef-a2ec-f79a1559bf3f.png)

2023-04-28 08:45 UTC, verdie-g requested changes

2023-04-28 08:45 UTC, verdie-g commented on src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
> +                        result = ((!isHuman) ? 1.2f : 2f);
Redundant parentheses.

2023-04-28 08:45 UTC, verdie-g commented on src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
> +                result = ((!isHuman) ? 0.8f : 1f);
Redundant parentheses.

2023-04-28 15:29 UTC, verdie-g approved these changes

2023-04-28 15:29 UTC, merged