mod : Shield taken by shield is now damage that weapons deals
verdie-g/crpg pull request #989
Opened 2023-05-18 19:59 UTC by namidaka

2023-05-19 21:46 UTC, verdie-g commented
![image](https://github.com/verdie-g/crpg/assets/9092290/590262a1-41b0-45de-828d-bd5b718598c6)

2023-05-20 22:13 UTC, verdie-g requested changes
Could you fix the PR name, I don't know what you mean.

2023-05-20 22:13 UTC, verdie-g requested changes
Could you fix the PR name, I don't know what you mean.

2023-05-20 22:18 UTC, namidaka commented
> Could you fix the PR name, I don't know what you mean.

my bad i thought you were talking about the pr. It's fixed. Basically , all weapon were doing the same damage no matter if they had 50c or 5c. I fixed it

2023-05-20 22:23 UTC, verdie-g requested changes

2023-05-20 22:23 UTC, verdie-g commented on src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
> +                        : weapon.CurrentUsageItem.SwingDamageFactor;
Coud you comment how you find out about that part. It doesn't seem intuitive.

Also I think you should get a warning for the redundant paranthesis.

2023-05-21 00:42 UTC, verdie-g approved these changes

2023-05-21 00:42 UTC, merged